### PR TITLE
feat: add localization editor and ide extension

### PR DESCRIPTION
**Pull request by NilsJacobsen**
> Hi together, let me know what I need to change in order to merge this

## Added a [localization editor](https://inlang.com/m/tdozzpar) & [ide extension](https://inlang.com/m/r7kp499g) for better i18n handling

- Faster message extraction
- Continuous i18n process improvements
- Improved translation status

### Editor -> Fink Translation Editor ([Open Editor](https://fink.inlang.com/github.com/NilsJacobsen/d1-manager))
image

### IDE Extension
image

## What I added
- Added `project.inlang/settings.json` file to configure the [inlang](https://inlang.com/) project.
- `repo id` file was generated by the SDK
- Added the extension to the vscode recommendations, so every contributor con benefit

## All opt-in
- I didn't change you setup, everybody can use what they want (opt-in)
- It's only a config

### CODE REVIEW

**Comment by JacobLinCool** [comment]
Wow! I had never heard of InLang before, but it seems like a cool toolkit for i18n!

I'm willing to merge this PR, but I am curious about two things:
1. Why choose InLang instead of other i18n collaboration tools like Crowdin?
2. Currently, I am using i18n-ally as my VSCode extension for i18n personally. Sometimes, I just rely on its auto-translation button. 😃 Will the new extension conflict with i18n-ally?

Also, I noticed that you have included a `project.inlang/project_id` file, and the Fink Translation Editor link you provided is pointing to your fork. I am not sure if this will cause any problems?

**Comment by NilsJacobsen** [comment]
Hi @JacobLinCool,

> Why choose InLang instead of other i18n collaboration tools like Crowdin?

Crowdin stores translations on their server -> syncing must be established. inlang is lazy cloning the repo in the browser and let you work directly on the files with a view that is made for translators. Other tools like the [ide extension](https://inlang.com/m/r7kp499g/app-inlang-ideExtension) or the [CLI](https://inlang.com/m/2qj2w8pu/app-inlang-cli) are working with the same approach. One source of truth, which leads to a single little settings file to configure.

> Currently, I am using i18n-ally as my VSCode extension for i18n personally. Sometimes, I just rely on its auto-translation button. 😃 Will the new extension conflict with i18n-ally?

You can continue using i18n ally. No worries. It's all opt-in. As far as I interpret the activity in their repo, I think it's not well maintained anymore, though. I recommend using the CLI in your build/test step to lint missing translations and/or machine translate -> [Guide](https://inlang.com/g/ssryldhd/guide-nilsjacobsen-automationSystem). But as I said, it's all opt-in.

**Comment by NilsJacobsen** [comment]
> Also, I noticed that you have included a project.inlang/project_id file, and the Fink Translation Editor link you provided is pointing to your fork. I am not sure if this will cause any problems?

The id is generated by the SDK and will also work when merging to main, so no worries.

**Review by JacobLinCool — APPROVED** [review]

**Comment by JacobLinCool** [comment]
Great! I'll give it a try. Thank you for the contribution.

**Pull request merged**
